services:
  db:
    image: postgres:17.7-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: ${DB_APP_USER}
      POSTGRES_PASSWORD: ${DB_APP_PASS}
    volumes:
      - "./data:/var/data/db"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_APP_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
  webserver:
    build: ./
    ports:
      - "9010:9010"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/impera-bot
      SPRING_DATASOURCE_USERNAME: ${DB_APP_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_APP_PASS}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      IMPERA_USERNAME: ${IMPERA_USER_NAME}
      IMPERA_PASSWORD: ${IMPERA_USER_PASSWORD}
